# Generated by Django 5.2 on 2025-10-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which topics should be presented')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='questions.topic')),
            ],
            options={
                'verbose_name': 'Code Snippet',
                'verbose_name_plural': 'Code Snippets',
                'ordering': ['topic', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('code', 'Code Challenge'), ('explanation', 'Explanation'), ('fill_blank', 'Fill in the Blank')], default='multiple_choice', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('question_text', models.TextField(help_text='The question to ask the user')),
                ('code_example', models.TextField(blank=True, help_text='Optional code example to show with the question')),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct_option', models.CharField(blank=True, help_text='A, B, C, or D', max_length=1)),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer for code/fill blank questions')),
                ('explanation', models.TextField(help_text='Explanation of the correct answer')),
                ('documentation_link', models.URLField(blank=True, help_text='Link to pandas documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['topic', 'difficulty', 'created_at'],
            },
        ),
    ]
