# Generated by Django 5.2 on 2025-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='documentation',
            field=models.TextField(blank=True, help_text='Detailed documentation/learning material for this topic'),
        ),
    ]
