# Generated by Django 5.2 on 2025-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_topic_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint for code challenges'),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Initial code template for code challenges'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.JSONField(blank=True, help_text="JSON array of test cases with 'input', 'expected_output' for validation", null=True),
        ),
    ]
