# Generated by Django 5.2 on 2025-10-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='documentation_viewed',
            field=models.BooleanField(default=False, help_text='Has user viewed the documentation for this topic'),
        ),
    ]
