# Generated by Django 5.2 on 2025-11-21 14:55

from django.db import migrations


def set_default_topics(apps, schema_editor):
    """Set default topic for users without one."""
    TelegramUser = apps.get_model('bot', 'TelegramUser')
    Topic = apps.get_model('questions', 'Topic')
    
    # Get default topic (first by order)
    default_topic = Topic.objects.order_by('order', 'name').first()
    
    if default_topic:
        # Update users without a current topic
        TelegramUser.objects.filter(current_topic__isnull=True).update(
            current_topic=default_topic
        )


def reverse_migration(apps, schema_editor):
    """Reverse is a no-op since we don't want to remove topics."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userprogress_documentation_viewed'),
        ('questions', '0001_initial'),  # Ensure topics exist
    ]

    operations = [
        migrations.RunPython(set_default_topics, reverse_migration),
    ]
